name: Build unypkg Base System

on: workflow_dispatch

env:
  UNY_AUTO_PAT: ${{ secrets.UNY_AUTO_PAT }}
  GH_TOKEN: ${{ secrets.UNY_AUTO_PAT }}

jobs:
  build-unypkg-system:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Save variables to files
        run: |
          echo "$UNY_AUTO_PAT" >UNY_AUTO_PAT
          echo "$GH_TOKEN" >GH_TOKEN
      - name: Run the build script
        run: |
          chmod +x unypkg-base-build.sh
          sudo ./unypkg-base-build.sh
