name: Build unypkg Base System

on: workflow_dispatch

env:
  UNY_AUTO_PAT: ${{ secrets.UNY_AUTO_PAT }}
  GH_TOKEN: ${{ secrets.UNY_AUTO_PAT }}

jobs:
  build-unypkg-stage-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Save variables to files
        run: |
          echo "$UNY_AUTO_PAT" >UNY_AUTO_PAT
          echo "$GH_TOKEN" >GH_TOKEN
      - name: Run stage1 script
        run: |
          chmod +x unypkg-base-build-stage1.sh
          sudo ./unypkg-base-build-stage1.sh
  build-unypkg-stage-2:
    needs: build-unypkg-stage-1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Save variables to files
        run: |
          echo "$UNY_AUTO_PAT" >UNY_AUTO_PAT
          echo "$GH_TOKEN" >GH_TOKEN
      - name: Run stage2 script
        run: |
          chmod +x unypkg-base-build-stage2.sh
          sudo ./unypkg-base-build-stage2.sh
